---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingress.baiding.tech
  resources:
  - apps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - yqc.tech.github.com
  resources:
  - apps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - yqc.tech.github.com
  resources:
  - apps/finalizers
  verbs:
  - update
- apiGroups:
  - yqc.tech.github.com
  resources:
  - apps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - yqc.tech.github.com
  resources:
  - serviceingresscontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - yqc.tech.github.com
  resources:
  - serviceingresscontrollers/finalizers
  verbs:
  - update
- apiGroups:
  - yqc.tech.github.com
  resources:
  - serviceingresscontrollers/status
  verbs:
  - get
  - patch
  - update
