# permissions for end users to view serviceingresscontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: serviceingresscontroller-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder
    app.kubernetes.io/part-of: kubebuilder
    app.kubernetes.io/managed-by: kustomize
  name: serviceingresscontroller-viewer-role
rules:
- apiGroups:
  - yqc.tech.github.com
  resources:
  - serviceingresscontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - yqc.tech.github.com
  resources:
  - serviceingresscontrollers/status
  verbs:
  - get
