apiVersion: yqc.tech.github.com/v1alpha1
kind: ServiceIngressController
metadata:
  name: serviceingresscontroller-sample
spec:
  image: nginx:latest
  replicas: 1
  enable_ingress: true
  enable_service: true
