---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-yqc-tech-github-com-v1alpha1-app
  failurePolicy: Fail
  name: mapp.kb.io
  rules:
  - apiGroups:
    - yqc.tech.github.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apps
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-yqc-tech-github-com-v1alpha1-serviceingresscontroller
  failurePolicy: Fail
  name: vserviceingresscontroller.kb.io
  rules:
  - apiGroups:
    - yqc.tech.github.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - serviceingresscontrollers
  sideEffects: None
